server:
  port: 9000
  netty:
    connection-timeout: 2s
    idle-timeout: 15s
  shutdown: graceful

spring:
  application:
    name: edge-service
  lifecycle:
    timeout-per-shutdown-phase: 15s
  cloud:
    httpclient:
      connect-timeout: 2000 # 2s
      response-timeout: 5s
      pool:
        type: elastic # 连接池类型的值可以是elastic、fixed或dsabled
        max-idle-time: 15s # 通信通道在关闭之前的空闲时间
        max-life-time: 60s # 通信通道将被关闭的时间
    gateway:
      default-filters: # 过滤器的名称
        - name: Retry # 默认过滤器的列表
          args:
            retries: 3
            methods: GET
            series: SERVER_ERROR # 仅当
            exceptions: java.io.IOException, java.util.concurrent.TimeoutException
            backoff:
              firstBackoff: 50ms
              maxBackOff: 500ms
              factor: 2
              basedOnPreviousValue: false
      routes:
        - id: catalog-route
          uri: ${CATALOG_SERVICE_URL:http://localhost:9001}/books/
          predicates:
            - Path=/books/**
          filters:
            - name: CircuitBreaker
              args:
                name: catalogCircuitBreaker
                fallbackUri: forward:/catalog-fallback # 当断路器处于打开状态时，要转发至该URI
        - id: order-route
          uri: ${ORDER_SERVICE_URL:http://localhost:9002}/orders/
          predicates:
            - Path=/orders/**
          filters:
            - name: CircuitBreaker
              args:
                name: orderCircuitBreaker
  redis:
    connect-timeout: 2s
    host: localhost
    port: 6379
    timeout: 1s
  session:
    store-type: redis
    timeout: 10m
    redis:
      namespace: polar:edge

resilience4j:
  circuitbreaker:
    configs:
      default: # 适用于所有断路器的默认配置bean
        slidingWindowSize: 20 # 当断路器处于关闭状态时，记录调用次数的滑动窗口大小
        permittedNumberOfCallsInHalfOpenState: 5 # 当断路器处于半开状态时，允许调用的请求数
        failureRateThreshold: 50 # 当失败率高于阈值时，断路器会被断开
        waitDurationInOpenState: 15000 # 从打开到半开的等待时间（毫秒）
  timelimiter:
    configs:
      default: # 适用于所有限时器的默认配置
        timeoutDuration: 5s # 配置超时（秒）

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{FULL} - %msg%n"
  level:
    io.github.resilience4j: DEBUG