server:
  port: 9000
  netty:
    connection-timeout: 2s
    idle-timeout: 15s
  shutdown: graceful

spring:
  application:
    name: edge-service
  lifecycle:
    timeout-per-shutdown-phase: 15s
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:8888
      request-connect-timeout: 5000 # 5s
      request-read-timeout: 5000 # 5s
      fail-fast: false # In production, set to true
      retry:
        max-attempts: 6
        initial-interval: 1000 # 1s
        max-interval: 2000 # 2s
        multiplier: 1.1
    gateway:
      server:
        webflux:
          httpclient:
            connect-timeout: 2000 # 2s
            response-timeout: 5s
            pool:
              type: elastic
              max-idle-time: 15s
              max-life-time: 60s
          default-filters:
            - SaveSession
            - TokenRelay # 当调用下游服务时，启动访问令牌的传播
            - name: RequestRateLimiter
              args:
                redis-rate-limiter:
                  replenishRate: 10 # 每秒钟放入存储桶中的令牌数量
                  burstCapacity: 20 # 允许暴增到20个请求
                  requestedTokens: 1 # 每个请求花费多少个令牌

            - name: Retry # 默认过滤器的列表
              args:
                retries: 3
                methods: GET
                series: SERVER_ERROR # 仅当
                exceptions: java.io.IOException, java.util.concurrent.TimeoutException
                backoff:
                  firstBackoff: 50ms
                  maxBackOff: 500ms
                  factor: 2
                  basedOnPreviousValue: false
          routes:
            - id: spa-route
              uri: ${SPA_URL:http://localhost:9004}
              predicates:
                - Path=/,/*.css,/*.js,/favicon.ico
            - id: catalog-route
              uri: ${CATALOG_SERVICE_URL:http://localhost:9001}/books/
              predicates:
                - Path=/books/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: catalogCircuitBreaker
                    fallbackUri: forward:/catalog-fallback # 当断路器处于打开状态时，要转发至该URI
            - id: order-route
              uri: ${ORDER_SERVICE_URL:http://localhost:9002}/orders/
              predicates:
                - Path=/orders/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: orderCircuitBreaker
  data:
    redis:
      connect-timeout: 2s
      host: localhost
      port: 6379
      timeout: 1s
  session:
    store-type: redis
    timeout: 10m
    redis:
      namespace: polar:edge
  security:
    oauth2:
      client:
        registration:
          keycloak: # 在Spring Security中识别客户端注册名称(叫做registrationId）。它可以是任意的字符串
            client-id: edge-service # Keycloak中所定义的OAuth2客户端标识符
            client-secret: polar-keycloak-secret # 客户端用来与Keycloak进行认证的共享Secret
            scope: openid,roles # 客户端希望能够访问的scope列表。 openid scope会在OAuth2之上触发OIDC认证
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/PolarBookshop

resilience4j:
  circuitbreaker:
    configs:
      default: # 适用于所有断路器的默认配置bean
        slidingWindowSize: 20 # 当断路器处于关闭状态时，记录调用次数的滑动窗口大小
        permittedNumberOfCallsInHalfOpenState: 5 # 当断路器处于半开状态时，允许调用的请求数
        failureRateThreshold: 50 # 当失败率高于阈值时，断路器会被断开
        waitDurationInOpenState: 15000 # 从打开到半开的等待时间（毫秒）
  timelimiter:
    configs:
      default: # 适用于所有限时器的默认配置
        timeoutDuration: 5s # 配置超时（秒）

#logging:
#  level:
#    io.github.resilience4j: DEBUG