apiVersion: networking.k8s.io/v1 # Ingress对象的API版本
kind: Ingress # 要创建的对象类型
metadata:
  name: polar-ingress # Ingress的名称
spec:
  ingressClassName: nginx # 配置负责管理该对象的Ingress控制器
  rules:
    - http: # HTTP流量的Ingress规则
        paths:
          - path: / # 所有请求的默认规则
            pathType: Prefix
            backend:
              service:
                name: edge-service # 要将流量转发至该Service对象
                port:
                  number: 80 # 要将流量转发至该Service的端口